### ISSUE TITLE
FR12. Display a menu of options to the user

### ISSUE THREAD

**Issue by humaira1526** [WSU-4110/2D-3D-Interior-Design1#15]
|FR12. Display a menu of options to the user |
|---|
|**Goal**: Allow user ease of control.|
**Stakeholders:** Home Owners, College Students, Interior Designers|
| **Description:** At the top of the interface, the user will be presented with buttons that will allow them to access certain features previously identified (undo/redo, furniture options, save/export, the color picker, navigation etc.) as well as information about the floorplan such as when it was last saved and the overall dimensions of the room. The buttons will have simple icons and/or names, and when the user hovers over them a small pop-up will briefly explain what the button does. |
| **Origin:** Group Meeting on 09/19/2023.|
| **Version:** 1.0  |  
|**Date:** 09/18/2023
|  **Priority:** 6 |

**Comment by Hannah-Hoover** [comment]
Buttons are functional and working on homepage
