### ISSUE TITLE
FR13.  Modification Not Possible 

### ISSUE THREAD

**Issue by humaira1526** [WSU-4110/2D-3D-Interior-Design1#17]
|FR13.  Modification Not Possible  |
|---|
|**Goal**: Inform the user if the modification to the room is not possible.|
**Stakeholders:** Home Owners, College Students, Interior Designers|
| **Description:** When the web app user sets the measurements of a room and tries to add a furniture piece that is too large it will inform the user that the modification is not possible. In the case where there is already a furniture piece in that area the app will also show the same message. |
| **Origin:** Group Meeting on 09/12/2023.|
| **Version:** 1.0  |  
|**Date:** 09/18/2023
|  **Priority:** 8 |

**Comment by Hannah-Hoover** [comment]
We do not have this implemented
